CREATE TABLE [cont].[Emails] (
    [ID]      INT            IDENTITY (1, 1) NOT NULL,
    [EmailTypeID]     TINYINT       NOT NULL,
    [Subject]   NVARCHAR (255)  NOT NULL,
    [Body] NVARCHAR (MAX) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

