//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("EyeTrackerModel", "FK_ClickInfos_VisitInfoId", "VisitInfos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EyeTracker.DAL.EntityModels.VisitInfo), "ClickInfos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EyeTracker.DAL.EntityModels.ClickInfo), true)]
[assembly: EdmRelationshipAttribute("EyeTrackerModel", "FK_VisitInfos_UserApplicationId", "UserApplications", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EyeTracker.DAL.EntityModels.UserApplication), "VisitInfos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EyeTracker.DAL.EntityModels.VisitInfo), true)]
[assembly: EdmRelationshipAttribute("EyeTrackerModel", "FK_ViewPartInfos_VisitInfoId", "VisitInfos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EyeTracker.DAL.EntityModels.VisitInfo), "ViewPartInfos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EyeTracker.DAL.EntityModels.ViewPartInfo), true)]

#endregion

namespace EyeTracker.DAL.EntityModels
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ClickInfo> ClickInfos
        {
            get
            {
                if ((_ClickInfos == null))
                {
                    _ClickInfos = base.CreateObjectSet<ClickInfo>("ClickInfos");
                }
                return _ClickInfos;
            }
        }
        private ObjectSet<ClickInfo> _ClickInfos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserApplication> UserApplications
        {
            get
            {
                if ((_UserApplications == null))
                {
                    _UserApplications = base.CreateObjectSet<UserApplication>("UserApplications");
                }
                return _UserApplications;
            }
        }
        private ObjectSet<UserApplication> _UserApplications;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ViewPartInfo> ViewPartInfos
        {
            get
            {
                if ((_ViewPartInfos == null))
                {
                    _ViewPartInfos = base.CreateObjectSet<ViewPartInfo>("ViewPartInfos");
                }
                return _ViewPartInfos;
            }
        }
        private ObjectSet<ViewPartInfo> _ViewPartInfos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VisitInfo> VisitInfos
        {
            get
            {
                if ((_VisitInfos == null))
                {
                    _VisitInfos = base.CreateObjectSet<VisitInfo>("VisitInfos");
                }
                return _VisitInfos;
            }
        }
        private ObjectSet<VisitInfo> _VisitInfos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserActivity> UserActivities
        {
            get
            {
                if ((_UserActivities == null))
                {
                    _UserActivities = base.CreateObjectSet<UserActivity>("UserActivities");
                }
                return _UserActivities;
            }
        }
        private ObjectSet<UserActivity> _UserActivities;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ClickInfos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClickInfos(ClickInfo clickInfo)
        {
            base.AddObject("ClickInfos", clickInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserApplications EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserApplications(UserApplication userApplication)
        {
            base.AddObject("UserApplications", userApplication);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ViewPartInfos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToViewPartInfos(ViewPartInfo viewPartInfo)
        {
            base.AddObject("ViewPartInfos", viewPartInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VisitInfos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVisitInfos(VisitInfo visitInfo)
        {
            base.AddObject("VisitInfos", visitInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserActivities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserActivities(UserActivity userActivity)
        {
            base.AddObject("UserActivities", userActivity);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EyeTrackerModel", Name="ClickInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ClickInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ClickInfo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="visitInfoId">Initial value of the VisitInfoId property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="clientX">Initial value of the ClientX property.</param>
        /// <param name="clientY">Initial value of the ClientY property.</param>
        public static ClickInfo CreateClickInfo(global::System.Int64 id, global::System.Int64 visitInfoId, global::System.DateTime date, global::System.Int32 clientX, global::System.Int32 clientY)
        {
            ClickInfo clickInfo = new ClickInfo();
            clickInfo.Id = id;
            clickInfo.VisitInfoId = visitInfoId;
            clickInfo.Date = date;
            clickInfo.ClientX = clientX;
            clickInfo.ClientY = clientY;
            return clickInfo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 VisitInfoId
        {
            get
            {
                return _VisitInfoId;
            }
            set
            {
                OnVisitInfoIdChanging(value);
                ReportPropertyChanging("VisitInfoId");
                _VisitInfoId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VisitInfoId");
                OnVisitInfoIdChanged();
            }
        }
        private global::System.Int64 _VisitInfoId;
        partial void OnVisitInfoIdChanging(global::System.Int64 value);
        partial void OnVisitInfoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientX
        {
            get
            {
                return _ClientX;
            }
            set
            {
                OnClientXChanging(value);
                ReportPropertyChanging("ClientX");
                _ClientX = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientX");
                OnClientXChanged();
            }
        }
        private global::System.Int32 _ClientX;
        partial void OnClientXChanging(global::System.Int32 value);
        partial void OnClientXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientY
        {
            get
            {
                return _ClientY;
            }
            set
            {
                OnClientYChanging(value);
                ReportPropertyChanging("ClientY");
                _ClientY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientY");
                OnClientYChanged();
            }
        }
        private global::System.Int32 _ClientY;
        partial void OnClientYChanging(global::System.Int32 value);
        partial void OnClientYChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EyeTrackerModel", "FK_ClickInfos_VisitInfoId", "VisitInfos")]
        public VisitInfo VisitInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VisitInfo>("EyeTrackerModel.FK_ClickInfos_VisitInfoId", "VisitInfos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VisitInfo>("EyeTrackerModel.FK_ClickInfos_VisitInfoId", "VisitInfos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<VisitInfo> VisitInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VisitInfo>("EyeTrackerModel.FK_ClickInfos_VisitInfoId", "VisitInfos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<VisitInfo>("EyeTrackerModel.FK_ClickInfos_VisitInfoId", "VisitInfos", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EyeTrackerModel", Name="UserActivity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserActivity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserActivity object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        public static UserActivity CreateUserActivity(global::System.Int64 id, global::System.DateTime date, global::System.Guid userId, global::System.Int16 type)
        {
            UserActivity userActivity = new UserActivity();
            userActivity.Id = id;
            userActivity.Date = date;
            userActivity.UserId = userId;
            userActivity.Type = type;
            return userActivity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> LinkedObjectId
        {
            get
            {
                return _LinkedObjectId;
            }
            set
            {
                OnLinkedObjectIdChanging(value);
                ReportPropertyChanging("LinkedObjectId");
                _LinkedObjectId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LinkedObjectId");
                OnLinkedObjectIdChanged();
            }
        }
        private Nullable<global::System.Int64> _LinkedObjectId;
        partial void OnLinkedObjectIdChanging(Nullable<global::System.Int64> value);
        partial void OnLinkedObjectIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.Int16 _Type;
        partial void OnTypeChanging(global::System.Int16 value);
        partial void OnTypeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EyeTrackerModel", Name="UserApplication")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserApplication : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserApplication object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        public static UserApplication CreateUserApplication(global::System.Int64 id, global::System.Guid userId, global::System.String name, global::System.DateTime createDate)
        {
            UserApplication userApplication = new UserApplication();
            userApplication.Id = id;
            userApplication.UserId = userId;
            userApplication.Name = name;
            userApplication.CreateDate = createDate;
            return userApplication;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EyeTrackerModel", "FK_VisitInfos_UserApplicationId", "VisitInfos")]
        public EntityCollection<VisitInfo> VisitInfos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VisitInfo>("EyeTrackerModel.FK_VisitInfos_UserApplicationId", "VisitInfos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VisitInfo>("EyeTrackerModel.FK_VisitInfos_UserApplicationId", "VisitInfos", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EyeTrackerModel", Name="ViewPartInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ViewPartInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ViewPartInfo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="visitInfoId">Initial value of the VisitInfoId property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="timeSpan">Initial value of the TimeSpan property.</param>
        /// <param name="scrollLeft">Initial value of the ScrollLeft property.</param>
        /// <param name="scrollTop">Initial value of the ScrollTop property.</param>
        public static ViewPartInfo CreateViewPartInfo(global::System.Int64 id, global::System.Int64 visitInfoId, global::System.DateTime date, global::System.Int32 timeSpan, global::System.Int32 scrollLeft, global::System.Int32 scrollTop)
        {
            ViewPartInfo viewPartInfo = new ViewPartInfo();
            viewPartInfo.Id = id;
            viewPartInfo.VisitInfoId = visitInfoId;
            viewPartInfo.Date = date;
            viewPartInfo.TimeSpan = timeSpan;
            viewPartInfo.ScrollLeft = scrollLeft;
            viewPartInfo.ScrollTop = scrollTop;
            return viewPartInfo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 VisitInfoId
        {
            get
            {
                return _VisitInfoId;
            }
            set
            {
                OnVisitInfoIdChanging(value);
                ReportPropertyChanging("VisitInfoId");
                _VisitInfoId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VisitInfoId");
                OnVisitInfoIdChanged();
            }
        }
        private global::System.Int64 _VisitInfoId;
        partial void OnVisitInfoIdChanging(global::System.Int64 value);
        partial void OnVisitInfoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TimeSpan
        {
            get
            {
                return _TimeSpan;
            }
            set
            {
                OnTimeSpanChanging(value);
                ReportPropertyChanging("TimeSpan");
                _TimeSpan = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeSpan");
                OnTimeSpanChanged();
            }
        }
        private global::System.Int32 _TimeSpan;
        partial void OnTimeSpanChanging(global::System.Int32 value);
        partial void OnTimeSpanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ScrollLeft
        {
            get
            {
                return _ScrollLeft;
            }
            set
            {
                OnScrollLeftChanging(value);
                ReportPropertyChanging("ScrollLeft");
                _ScrollLeft = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ScrollLeft");
                OnScrollLeftChanged();
            }
        }
        private global::System.Int32 _ScrollLeft;
        partial void OnScrollLeftChanging(global::System.Int32 value);
        partial void OnScrollLeftChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ScrollTop
        {
            get
            {
                return _ScrollTop;
            }
            set
            {
                OnScrollTopChanging(value);
                ReportPropertyChanging("ScrollTop");
                _ScrollTop = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ScrollTop");
                OnScrollTopChanged();
            }
        }
        private global::System.Int32 _ScrollTop;
        partial void OnScrollTopChanging(global::System.Int32 value);
        partial void OnScrollTopChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EyeTrackerModel", "FK_ViewPartInfos_VisitInfoId", "VisitInfos")]
        public VisitInfo VisitInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VisitInfo>("EyeTrackerModel.FK_ViewPartInfos_VisitInfoId", "VisitInfos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VisitInfo>("EyeTrackerModel.FK_ViewPartInfos_VisitInfoId", "VisitInfos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<VisitInfo> VisitInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VisitInfo>("EyeTrackerModel.FK_ViewPartInfos_VisitInfoId", "VisitInfos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<VisitInfo>("EyeTrackerModel.FK_ViewPartInfos_VisitInfoId", "VisitInfos", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EyeTrackerModel", Name="VisitInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VisitInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VisitInfo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userApplicationId">Initial value of the UserApplicationId property.</param>
        /// <param name="ip">Initial value of the Ip property.</param>
        /// <param name="pageUri">Initial value of the PageUri property.</param>
        /// <param name="client">Initial value of the Client property.</param>
        /// <param name="software">Initial value of the Software property.</param>
        /// <param name="screenWidth">Initial value of the ScreenWidth property.</param>
        /// <param name="screenHeight">Initial value of the ScreenHeight property.</param>
        /// <param name="clientWidth">Initial value of the ClientWidth property.</param>
        /// <param name="clientHeight">Initial value of the ClientHeight property.</param>
        public static VisitInfo CreateVisitInfo(global::System.Int64 id, global::System.Int64 userApplicationId, global::System.String ip, global::System.String pageUri, global::System.Int32 client, global::System.Int32 software, global::System.Int32 screenWidth, global::System.Int32 screenHeight, global::System.Int32 clientWidth, global::System.Int32 clientHeight)
        {
            VisitInfo visitInfo = new VisitInfo();
            visitInfo.Id = id;
            visitInfo.UserApplicationId = userApplicationId;
            visitInfo.Ip = ip;
            visitInfo.PageUri = pageUri;
            visitInfo.Client = client;
            visitInfo.Software = software;
            visitInfo.ScreenWidth = screenWidth;
            visitInfo.ScreenHeight = screenHeight;
            visitInfo.ClientWidth = clientWidth;
            visitInfo.ClientHeight = clientHeight;
            return visitInfo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserApplicationId
        {
            get
            {
                return _UserApplicationId;
            }
            set
            {
                OnUserApplicationIdChanging(value);
                ReportPropertyChanging("UserApplicationId");
                _UserApplicationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserApplicationId");
                OnUserApplicationIdChanged();
            }
        }
        private global::System.Int64 _UserApplicationId;
        partial void OnUserApplicationIdChanging(global::System.Int64 value);
        partial void OnUserApplicationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ip
        {
            get
            {
                return _Ip;
            }
            set
            {
                OnIpChanging(value);
                ReportPropertyChanging("Ip");
                _Ip = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ip");
                OnIpChanged();
            }
        }
        private global::System.String _Ip;
        partial void OnIpChanging(global::System.String value);
        partial void OnIpChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> PreviousVisitInfoId
        {
            get
            {
                return _PreviousVisitInfoId;
            }
            set
            {
                OnPreviousVisitInfoIdChanging(value);
                ReportPropertyChanging("PreviousVisitInfoId");
                _PreviousVisitInfoId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PreviousVisitInfoId");
                OnPreviousVisitInfoIdChanged();
            }
        }
        private Nullable<global::System.Int64> _PreviousVisitInfoId;
        partial void OnPreviousVisitInfoIdChanging(Nullable<global::System.Int64> value);
        partial void OnPreviousVisitInfoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PageUri
        {
            get
            {
                return _PageUri;
            }
            set
            {
                OnPageUriChanging(value);
                ReportPropertyChanging("PageUri");
                _PageUri = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PageUri");
                OnPageUriChanged();
            }
        }
        private global::System.String _PageUri;
        partial void OnPageUriChanging(global::System.String value);
        partial void OnPageUriChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Client
        {
            get
            {
                return _Client;
            }
            set
            {
                OnClientChanging(value);
                ReportPropertyChanging("Client");
                _Client = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Client");
                OnClientChanged();
            }
        }
        private global::System.Int32 _Client;
        partial void OnClientChanging(global::System.Int32 value);
        partial void OnClientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Software
        {
            get
            {
                return _Software;
            }
            set
            {
                OnSoftwareChanging(value);
                ReportPropertyChanging("Software");
                _Software = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Software");
                OnSoftwareChanged();
            }
        }
        private global::System.Int32 _Software;
        partial void OnSoftwareChanging(global::System.Int32 value);
        partial void OnSoftwareChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ScreenWidth
        {
            get
            {
                return _ScreenWidth;
            }
            set
            {
                OnScreenWidthChanging(value);
                ReportPropertyChanging("ScreenWidth");
                _ScreenWidth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ScreenWidth");
                OnScreenWidthChanged();
            }
        }
        private global::System.Int32 _ScreenWidth;
        partial void OnScreenWidthChanging(global::System.Int32 value);
        partial void OnScreenWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ScreenHeight
        {
            get
            {
                return _ScreenHeight;
            }
            set
            {
                OnScreenHeightChanging(value);
                ReportPropertyChanging("ScreenHeight");
                _ScreenHeight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ScreenHeight");
                OnScreenHeightChanged();
            }
        }
        private global::System.Int32 _ScreenHeight;
        partial void OnScreenHeightChanging(global::System.Int32 value);
        partial void OnScreenHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientWidth
        {
            get
            {
                return _ClientWidth;
            }
            set
            {
                OnClientWidthChanging(value);
                ReportPropertyChanging("ClientWidth");
                _ClientWidth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientWidth");
                OnClientWidthChanged();
            }
        }
        private global::System.Int32 _ClientWidth;
        partial void OnClientWidthChanging(global::System.Int32 value);
        partial void OnClientWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientHeight
        {
            get
            {
                return _ClientHeight;
            }
            set
            {
                OnClientHeightChanging(value);
                ReportPropertyChanging("ClientHeight");
                _ClientHeight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientHeight");
                OnClientHeightChanged();
            }
        }
        private global::System.Int32 _ClientHeight;
        partial void OnClientHeightChanging(global::System.Int32 value);
        partial void OnClientHeightChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EyeTrackerModel", "FK_ClickInfos_VisitInfoId", "ClickInfos")]
        public EntityCollection<ClickInfo> ClickInfos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ClickInfo>("EyeTrackerModel.FK_ClickInfos_VisitInfoId", "ClickInfos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ClickInfo>("EyeTrackerModel.FK_ClickInfos_VisitInfoId", "ClickInfos", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EyeTrackerModel", "FK_VisitInfos_UserApplicationId", "UserApplications")]
        public UserApplication UserApplication
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserApplication>("EyeTrackerModel.FK_VisitInfos_UserApplicationId", "UserApplications").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserApplication>("EyeTrackerModel.FK_VisitInfos_UserApplicationId", "UserApplications").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserApplication> UserApplicationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserApplication>("EyeTrackerModel.FK_VisitInfos_UserApplicationId", "UserApplications");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserApplication>("EyeTrackerModel.FK_VisitInfos_UserApplicationId", "UserApplications", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EyeTrackerModel", "FK_ViewPartInfos_VisitInfoId", "ViewPartInfos")]
        public EntityCollection<ViewPartInfo> ViewPartInfos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ViewPartInfo>("EyeTrackerModel.FK_ViewPartInfos_VisitInfoId", "ViewPartInfos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ViewPartInfo>("EyeTrackerModel.FK_ViewPartInfos_VisitInfoId", "ViewPartInfos", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
