CREATE TABLE [dbo].[Cities] (
    [ID]   INT            IDENTITY (1, 1) NOT NULL,
    [Name] NVARCHAR (100) NOT NULL,
    [Latitude] FLOAT NOT NULL,
    [Longitude] FLOAT NOT NULL,
	[RegionID]	INT	NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);
GO

ALTER TABLE [dbo].[Cities]
ADD CONSTRAINT [FK_Cities_Region] FOREIGN KEY ([RegionID]) REFERENCES [dbo].[Regions] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

