CREATE TABLE [dbo].[Regions] (
    [Id]   INT            IDENTITY (1, 1) NOT NULL,
    [Name] NVARCHAR (100) NOT NULL,
	[CountryID]	INT	NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);
GO

ALTER TABLE [dbo].[Regions]
ADD CONSTRAINT [FK_Regions_Country] FOREIGN KEY ([CountryID]) REFERENCES [dbo].[Countries] ([GeoID]) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO
