CREATE TABLE [cont].[Items] (
    [ID]     INT            IDENTITY (1, 1) NOT NULL,
    [Key]    NVARCHAR (50)  NOT NULL,
    [SubKey] NVARCHAR (50)  NOT NULL,
    [Value]  NVARCHAR (MAX) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

