CREATE TABLE [dbo].[GeoKeys] (
    [Id]   INT            IDENTITY (1, 1) NOT NULL,
    [Key] NVARCHAR (100) NOT NULL,
	[CityID]	INT	NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);
GO

ALTER TABLE [dbo].[GeoKeys]
ADD CONSTRAINT [FK_GeoKeys_City] FOREIGN KEY ([CityID]) REFERENCES [dbo].[Cities] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

